-- liquibase formatted sql

-- changeset author:1
CREATE TABLE student (
                         student_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                         username VARCHAR(100) UNIQUE NOT NULL,
                         password VARCHAR(255) NOT NULL,
                         role VARCHAR(50) NOT NULL DEFAULT 'ROLE_STUDENT',
                         enabled BOOLEAN DEFAULT TRUE,
                         full_name_en VARCHAR(200) NOT NULL,
                         full_name_ar VARCHAR(200) NOT NULL,
                         email VARCHAR(150) UNIQUE NOT NULL,
                         telephone VARCHAR(30),
                         address VARCHAR(255),
                         last_login_at TIMESTAMP,
                         created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- changeset author:2
CREATE TABLE course (
                        course_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        course_name_en VARCHAR(200) NOT NULL,
                        course_name_ar VARCHAR(200) NOT NULL,
                        course_code VARCHAR(50) UNIQUE NOT NULL,
                        description VARCHAR(500),
                        credits INT CHECK (credits > 0),
                        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- changeset author:3
CREATE TABLE student_course (
                                student_id BIGINT NOT NULL,
                                course_id BIGINT NOT NULL,
                                enrolled_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                                PRIMARY KEY (student_id, course_id),
                                CONSTRAINT fk_student FOREIGN KEY (student_id) REFERENCES student(student_id) ON DELETE CASCADE,
                                CONSTRAINT fk_course FOREIGN KEY (course_id) REFERENCES course(course_id) ON DELETE CASCADE
);

-- changeset author:4
-- Insert sample students (passwords should be encoded with BCrypt in real apps)
INSERT INTO student (username, password, role, full_name_en, full_name_ar, email, telephone, address)
VALUES
    ('ali', '{noop}password', 'ROLE_STUDENT', 'Ali Hassan', 'علي حسن', 'ali@example.com', '+966512345678', 'Riyadh, Saudi Arabia'),
    ('sara', '{noop}password', 'ROLE_STUDENT', 'Sara Ahmed', 'سارة أحمد', 'sara@example.com', '+966511223344', 'Jeddah, Saudi Arabia'),
    ('admin', '{noop}admin123', 'ROLE_ADMIN', 'System Admin', 'مدير النظام', 'admin@example.com', '+966500000000', 'HQ');

-- changeset author:5
INSERT INTO course (course_name_en, course_name_ar, course_code, description, credits)
VALUES
    ('Database Systems', 'نظم قواعد البيانات', 'CS101', 'Intro to databases', 3),
    ('Software Engineering', 'هندسة البرمجيات', 'CS201', 'Software development principles', 4),
    ('Algorithms', 'الخوارزميات', 'CS301', 'Algorithm design and analysis', 3);

-- changeset author:6
INSERT INTO student_course (student_id, course_id) VALUES
                                                       (1, 1), -- Ali → Database Systems
                                                       (1, 2), -- Ali → Software Engineering
                                                       (2, 1), -- Sara → Database Systems
                                                       (3, 3); -- Admin → Algorithms (just as example)
